name: DekitateEvents
main: com.dekitateserver.events.DekitateEventsPlugin
version: 1.0.0-SNAPSHOT
author: ken_kentan
website: https://www.dekitateserver.com
depend: [DekitateCore]

api-version: '1.13'

commands:
  event:
    description: DekitateEventsコマンド
    usage: §e'/<command> help'でヘルプを確認してください.
    permission: event
    permission-message: §cこのコマンドを実行する権限がありません.
  parkour:
    description: Parkourコマンド
    usage: §e'/<command> help'でヘルプを確認してください.
    permission: event.parkour
    permission-message: §cこのコマンドを実行する権限がありません.
  gacha:
    description: Gachaコマンド
    usage: §e'/<command> help'でヘルプを確認してください.
    permission: event.gacha
    permission-message: §cこのコマンドを実行する権限がありません.
  key:
    description: Keyコマンド
    usage: §e'/<command> help'でヘルプを確認してください.
    permission: event.key
    permission-message: §cこのコマンドを実行する権限がありません.
  password:
    description: Passwordコマンド
    usage: §e'/<command> help'でヘルプを確認してください.
    permission: events.password
    permission-message: §cこのコマンドを実行する権限がありません.
  loginbonus:
    description: LoginBonusコマンド
    usage: §e'/<command> help'でヘルプを確認してください.
    permission: event.loginbonus
    permission-message: §cこのコマンドを実行する権限がありません.
